fixed backup creation
europ/atacac pull request #5
Opened 2020-05-25 12:41 UTC by europ

* backup.py performs a backup of all assets from tower that are listed in the repository
* supports all type of assets such as job_templates, projects, inventories, etc.
* it does not need label that was available only for job_templates

2020-06-03 10:09 UTC, fpob requested changes

2020-06-03 10:09 UTC, fpob commented on atacac/backup.py
>  @click.argument('label_id', envvar='LABEL_ID')
You can remove `label_id` since it is not used. Also remove it from example `.gitlab-ci.yml`.

2020-06-05 07:49 UTC, europ commented on atacac/backup.py
>  @click.argument('label_id', envvar='LABEL_ID')
I removed that line. BTW, the `LABEL_ID` is needed for the `synchronization.py`, I will keep it in `.gitlab-ci.yml` until then. The `synchronization.py` is going to be fixed separately.

2020-06-05 17:48 UTC, fpob approved these changes

2020-06-05 18:17 UTC, merged